### ISSUE TITLE
Not long enough

### ISSUE THREAD

**Issue by Xiarno** [thunderysteak/thunderysteak.github.io#1] opened 2020-02-17 23:16 UTC
Hey, on this page: https://github.com/thunderysteak/thunderysteak.github.io/blob/master/sfm-best-quality.md

The setting you give here:

`sfm.exe -nosteam -nop4 -num_edicts 8192 -sfm_resolution 2160 -sfm_shadowmapres 8192 -monitortexturesize 1024 -r_novis 1 -reflectiontexturesize 1024 +mat_envmapsize 256  mat_forceaniso 16 +r_waterforceexpensive 1 +r_waterforcereflectentities 1 +mat_wateroverlaysize 1024 +r_hunkalloclightmaps 0 +flex_smooth 0
`

It's so long that it doesn't even enter in the launch properties. It just cut at "+r_waterforceexpen"

**Comment by thunderysteak** [comment] 2020-02-18 00:03
Fixed in commit to mention the issue:  https://github.com/thunderysteak/thunderysteak.github.io/commit/e0e500e8d568f635fdd2488729e0e98bce356096
Its an issue caused by having Steam and SFM installed under Program Files (x86), which makes it hit the character limit. You'll have to use a batch script to execute it with all of the flags.

I quickly wrote a batch script that you can use. It also contains a warning message every time you launch SFM with those flags.
https://github.com/thunderysteak/script-collection/blob/master/sfm-high-quality-render.bat

**Closed as completed by thunderysteak** 2020-02-18 00:03 UTC
